config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
    #root "todos#index"
  resources :todos


  #get 'home/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :taskname, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable


  has_many :notification, as: :recipient       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  


    if user_signed_in?
      redirect_to todos_path
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show 
    @todo = Todo.find(params[:id])
  end

  def new
    @todo =Todo.new
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to @todo
    else
      render:new
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])

    if @todo.update(todo_params)
      redirect_to @todo
    else
      render :edit
    end
  end

  def destroy
    
    @todo = Todo.find(params[:id])
    @todo.destroy

    redirect_to root_path
  end

  private
  def todo_params
    params.require(:todo).permit(:task_id, :taskname, :tasktype, :duedatetime, :repeat)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/index.html.erb
<% name = current_user.present? ? current_user.email : 'Todo App' %>
<h1> Welcome To, <%= name %> </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <a class="navbar-brand text-primary" href="/">Todo App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete,  class: 'nav-link text-danger' %>
      </li>
      <% else %>
      <li class="nav-item">
      <%= link_to 'Login ', new_user_session_path, class: 'nav-link text-primary' %>
      </li>


      <li class="nav-item">
      <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link text-primary' %>
      </li>
      <% end %>
     
    </ul>
  </div>
</nav>

app/views/todos/_form.html.erb
<html>
<head>
  <style>
 
  input,
.btn {
 width: 100%;
 padding: 5px;
 border: primary;
 border-radius: 4px;
 margin: 5px 0;
 opacity: 0.85;
 display: inline-block;
 font-size: 17px;
 line-height: 20px;
 text-decoration: none; /* remove underline from anchors */
}


</style>

</head>
<body>
<div class="container h-100 ">
<%= form_with model: @todo do |form| %>
    <div class="container">
      <%= form.label :taskname %><br>
      <%= form.text_field :taskname  %>
    </div>
  
    <div class="container">
      <%= form.label :tasktype %><br>
      <%= form.select :tasktype, ['Please Select Task', 'Personal','Work','Other'] ,{}, {class: "form-control"} %>

    </div>
  
  
    <div class="container">
      <%= form.label :duedatetime %><br>
      <%= form.datetime_field :duedatetime %>
    </div>
  
  
    <div class="container">
      <%= form.label :repeat %><br>
      
      <%= form.select :repeat, ['Oneday','Weekly','Month','Year'] ,{}, {class: "form-control"} %> 
    </div>
   
    <br/>
    <div class="d-grid gap-2 col-2 mx-auto">
    <%= form.submit  %>
    </div>
  <% end %>

app/views/todos/edit.html.erb
<h1 class="text-center text-primary">Edit Task</h1><hr>

<%= render "form", todo: @todo %>

app/views/todos/index.html.erb
<h1 class="text-center">Task Listing</h1>
<%= link_to "New Task", new_todo_path , class:"btn btn-info my-2"%>
<hr>
<ul>
  <% @todos.each do |todo| %>
    <li>
      <%= link_to todo.taskname, todo %>
      
    </li>
  <% end %>
</ul>

app/views/todos/new.html.erb
<html>
<head>
  <style>
 
  input,
.btn {
 width: 100%;
 padding: 12px;
 border: primary;
 border-radius: 4px;
 margin: 5px 0;
 opacity: 0.85;
 display: inline-block;
 font-size: 17px;
 line-height: 20px;
 text-decoration: none; /* remove underline from anchors */
}


</style>

</head>
<body>
<div class="container h-100 ">
<h1>New Task</h1>
<%= render "form", todo: @todo %>

app/views/todos/show.html.erb
<h1 class= "text-center text-primary"> View Information</h1> <hr>


<p><strong> Taskname:- </strong>
<%= @todo.taskname %></p>

<p>
<strong> Tasktype:- </strong>
<%= @todo.tasktype %></p>
<p>
<strong> Due date time:- </strong>
<%= @todo.duedatetime %></p>
<p>
<strong> Repeat:- </strong>
<%= @todo.repeat %></p>

<ul>
  <li><%= link_to "Edit", edit_todo_path(@todo), class:"btn btn-success" %></li></br>
  <li><%= link_to "Destroy", todo_path(@todo), method: :delete, data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } , class: "btn btn-danger" %></li>
</ul>